version: '3.7'

services:
  web:
    container_name: 'countries'
    image: 'info-of-countries'
    build: .
    environment:
#      Настраиваем доступ к контейнеру с backend
#      настраиваемые переменные: [имя контейнера]:[номер хоста(внутренний)]
      - API_CBR=https://www.cbr-xml-daily.ru
      - API_COUNTRIES=https://restcountries.com/v3.1/
      - API_UNIVERSITIES=http://universities.hipolabs.com
    ports:
      - '80:80'
